version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: google-cloud-storage
    versions:
    - 1.35.0
    - 1.35.1
    - 1.36.0
    - 1.36.1
    - 1.36.2
    - 1.37.0
    - 1.37.1
  - dependency-name: pillow
    versions:
    - 8.1.0
    - 8.1.1
    - 8.1.2
  - dependency-name: django-health-check
    versions:
    - 3.16.2
    - 3.16.3
  - dependency-name: sentry-sdk
    versions:
    - 0.19.5
    - 0.20.0
    - 0.20.1
    - 0.20.2
    - 0.20.3
  - dependency-name: django
    versions:
    - 2.2.13
