version: "3.7"
services:
  db:
    image: postgres:10.1-alpine
  web:
    build:
      context: .
      dockerfile: DockerfileTest
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
    volumes:
      - .:/base_site
    depends_on:
      - db
    command: ["./wait-for-it.sh", "${DB_HOST}:${DB_PORT}", "-t", "120", "--", "./base_site.sh"]

  integration-tests:
    image: python:3.7.4-slim
    env_file: .env
    volumes:
      - .:/base_site
    depends_on:
      - db
    command: >
      sh -c "pip install tox && cd base_site && tox"
