version: "3.5"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: base_site
    command: --default-authentication-plugin=mysql_native_password
  isabele:
    build: .
    ports:
      - "5007:5005"
    env_file: .env
    volumes:
      - .:/base_site
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "-t", "120", "--", "./base_site.sh"]