# Generated by Django 2.2.5 on 2019-09-21 17:17

import ckeditor.fields
from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Título')),
                ('text', models.CharField(max_length=2000, verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Coaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_services', models.CharField(max_length=200, null=True, verbose_name='Título Serviços Coaching')),
                ('youtube_url', models.URLField(help_text='https://www.youtube.com/embed/bEVO6klt3_o?rel=0&amp;showinfo=0', max_length=3000, verbose_name='YouTube Vídeo URL')),
            ],
            options={
                'verbose_name': 'Coaching',
                'verbose_name_plural': 'Coachings',
            },
        ),
        migrations.CreateModel(
            name='ComplexServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('text', models.CharField(max_length=2000, verbose_name='Texto')),
                ('service', models.IntegerField(choices=[(1, 'Psicologia'), (2, 'Coaching')], default=1, verbose_name='Onde Exibir?')),
            ],
            options={
                'verbose_name': 'Serviço Complexo',
                'verbose_name_plural': 'Serviços Complexo',
            },
        ),
        migrations.CreateModel(
            name='Deposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='Autor')),
                ('text', models.CharField(max_length=2000, verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_about', models.CharField(help_text='Sobre', max_length=30, verbose_name='Título Sobre')),
                ('text_about', ckeditor.fields.RichTextField(verbose_name='Texto Sobre')),
                ('whatsapp_api_url', models.URLField(help_text='https://api.whatsapp.com/send?phone=5511992323959&amp;text=Acabei%20de%20ver%20o%20seu%20site%2C%20gostaria%20de%20mais%20informa%C3%A7%C3%B5es%20sobre...', max_length=3000, verbose_name='WhatsApp API URL')),
                ('telfone', models.CharField(help_text='+55 11 9 7789-2344', max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='isabele@isabelelucchesi.com', max_length=254, verbose_name='E-Mail')),
                ('email_subject', models.CharField(help_text='Mais informações obre o tendimento.', max_length=200, null=True, verbose_name='Assunto do E-mail')),
                ('title_depositions', models.CharField(max_length=200, null=True, verbose_name='Título Depoimentos')),
                ('title_contacts', models.CharField(max_length=200, null=True, verbose_name='Título Contatos')),
                ('title_enderecos', models.CharField(max_length=200, null=True, verbose_name='Título Endereços')),
                ('link_maps', models.URLField(help_text='https://www.google.com/maps/d/embed?mid=1PBARGGfXbqBOh_8T84kqYuz4qM87PJQW', max_length=1500, null=True, verbose_name='Url para o maps')),
                ('link_facebook', models.URLField(max_length=1000, null=True, verbose_name='Facebook')),
                ('link_linkedin', models.URLField(max_length=1000, null=True, verbose_name='Linkedin')),
                ('link_instagram', models.URLField(max_length=1000, null=True, verbose_name='Instagram')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_image', verbose_name='Imagem Sobre')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '334x334', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Crop Imagem Sobre')),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt da imagem Sobre')),
                ('header_text', ckeditor.fields.RichTextField(null=True, verbose_name='Texto do Header')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='Psychology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_services', models.CharField(max_length=200, null=True, verbose_name='Título Serviços Psicologia')),
                ('youtube_url', models.URLField(help_text='https://www.youtube.com/embed/bEVO6klt3_o?rel=0&amp;showinfo=0', max_length=3000, verbose_name='YouTube Vídeo URL')),
            ],
            options={
                'verbose_name': 'Psicologia',
                'verbose_name_plural': 'Psicologias',
            },
        ),
        migrations.CreateModel(
            name='SimpleServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000, verbose_name='Texto')),
                ('service', models.IntegerField(choices=[(1, 'Psicologia'), (2, 'Coaching')], default=1, verbose_name='Onde Exibir?')),
            ],
            options={
                'verbose_name': 'Serviço Simples',
                'verbose_name_plural': 'Serviços Simples',
            },
        ),
    ]
