# Generated by Django 2.2.7 on 2020-08-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='whatsapp_api_url',
            field=models.URLField(help_text='https://api.whatsapp.com/send?phone=5511992323959&amp;text=Acabei%20de%20ver%20o%20seu%20site%2C%20gostaria%20de%20mais%20informa%C3%A7%C3%B5es%20sobre...', max_length=3000, verbose_name='WhatsApp API URL'),
        ),
    ]
