# Generated by Django 2.0.5 on 2018-05-26 22:06

import ckeditor_uploader.fields
from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=70, verbose_name='Title')),
                ('image', models.ImageField(blank=True, upload_to='uploaded_images', verbose_name='Image')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '430x360', adapt_rotation=False,
                                                                   allow_fullsize=False, free_crop=False,
                                                                   help_text=None,
                                                                   hide_image_field=False, size_warning=False,
                                                                   verbose_name='Crop Image')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='contents')),
            ],
        ),
    ]
