# Generated by Django 2.0.7 on 2018-09-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_about', models.CharField(help_text='Sobre', max_length=30, verbose_name='Title Sobre')),
                ('text_about', models.TextField(verbose_name='Texto Sobre')),
                ('youtube_url', models.URLField(help_text='https://www.youtube.com/embed/bEVO6klt3_o?rel=0&amp;showinfo=0', max_length=3000, verbose_name='YouTube Vídeo URL')),
                ('whatsapp_api_url', models.URLField(help_text='https://api.whatsapp.com/send?phone=5511992323959&amp;text=Acabei%20de%20ver%20o%20seu%20site%2C%20gostaria%20de%20mais%20informa%C3%A7%C3%B5es%20sobre...', max_length=3000, verbose_name='WhatsApp API URL')),
                ('telfone', models.CharField(help_text='+55 11 9 7789-2344', max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='isabele@isabelelucchesi.com', max_length=254, verbose_name='E-Mail')),
            ],
        ),
    ]
