# Generated by Django 2.0.7 on 2018-09-05 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'Home', 'verbose_name_plural': 'Homes'},
        ),
    ]
