# Generated by Django 2.1.1 on 2018-09-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20180905_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Título')),
                ('text', models.CharField(max_length=2000, verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='ComplexServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('text', models.CharField(max_length=2000, verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Serviço Complexo',
                'verbose_name_plural': 'Serviços Complexo',
            },
        ),
        migrations.CreateModel(
            name='Deposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='Autor')),
                ('text', models.CharField(max_length=2000, verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
            },
        ),
        migrations.CreateModel(
            name='SimpleServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000, verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Serviço Simples',
                'verbose_name_plural': 'Serviços Simples',
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='ModelExample',
        ),
        migrations.AddField(
            model_name='index',
            name='link_facebook',
            field=models.URLField(max_length=1000, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='index',
            name='link_instagram',
            field=models.URLField(max_length=1000, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='index',
            name='link_linkedin',
            field=models.URLField(max_length=1000, null=True, verbose_name='Linkedin'),
        ),
        migrations.AddField(
            model_name='index',
            name='link_maps',
            field=models.URLField(help_text='https://www.google.com/maps/d/embed?mid=1PBARGGfXbqBOh_8T84kqYuz4qM87PJQW', max_length=1500, null=True, verbose_name='Url para o maps'),
        ),
        migrations.AddField(
            model_name='index',
            name='link_twitter',
            field=models.URLField(max_length=1000, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='index',
            name='title_contacts',
            field=models.CharField(max_length=200, null=True, verbose_name='Título Contatos'),
        ),
        migrations.AddField(
            model_name='index',
            name='title_depositions',
            field=models.CharField(max_length=200, null=True, verbose_name='Título Depoimentos'),
        ),
        migrations.AddField(
            model_name='index',
            name='title_enderecos',
            field=models.CharField(max_length=200, null=True, verbose_name='Título Endereços'),
        ),
        migrations.AddField(
            model_name='index',
            name='title_services',
            field=models.CharField(max_length=200, null=True, verbose_name='Título Serviços'),
        ),
        migrations.AlterField(
            model_name='index',
            name='title_about',
            field=models.CharField(help_text='Sobre', max_length=30, verbose_name='Título Sobre'),
        ),
    ]
