# Generated by Django 2.1.1 on 2018-09-14 00:12

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20180912_0255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AddField(
            model_name='index',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Crop Imagem Sobre'),
        ),
        migrations.AddField(
            model_name='index',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_image', verbose_name='Imagem Sobre'),
        ),
    ]
