# Generated by Django 2.1.1 on 2018-09-15 15:42

from django.db import migrations, models
import storages.backends.gcloud


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20180914_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='test',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='teste', verbose_name='teste'),
        ),
    ]
