# Generated by Django 2.1.1 on 2018-09-15 16:18

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_index_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '300x450', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Crop Imagem Sobre'),
        ),
    ]
