# Generated by Django 2.1.1 on 2018-09-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20180915_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='test',
        ),
        migrations.AddField(
            model_name='index',
            name='image_alt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt da imagem Sobre'),
        ),
    ]
