# Generated by Django 2.0.8 on 2018-09-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20180915_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_services', models.CharField(max_length=200, null=True, verbose_name='Título Serviços Coaching')),
                ('youtube_url', models.URLField(help_text='https://www.youtube.com/embed/bEVO6klt3_o?rel=0&amp;showinfo=0', max_length=3000, verbose_name='YouTube Vídeo URL')),
            ],
            options={
                'verbose_name': 'Coaching',
                'verbose_name_plural': 'Coachings',
            },
        ),
        migrations.CreateModel(
            name='Psychology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_services', models.CharField(max_length=200, null=True, verbose_name='Título Serviços Psicologia')),
                ('youtube_url', models.URLField(help_text='https://www.youtube.com/embed/bEVO6klt3_o?rel=0&amp;showinfo=0', max_length=3000, verbose_name='YouTube Vídeo URL')),
            ],
            options={
                'verbose_name': 'Psicologia',
                'verbose_name_plural': 'Psicologias',
            },
        ),
        migrations.RemoveField(
            model_name='index',
            name='title_services',
        ),
        migrations.RemoveField(
            model_name='index',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='complexservices',
            name='service',
            field=models.IntegerField(choices=[(1, 'Psicologia'), (2, 'Coaching')], default=1, verbose_name='Onde Exibir?'),
        ),
        migrations.AddField(
            model_name='simpleservices',
            name='service',
            field=models.IntegerField(choices=[(1, 'Psicologia'), (2, 'Coaching')], default=1, verbose_name='Onde Exibir?'),
        ),
    ]
