# Generated by Django 2.0.8 on 2018-09-23 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20180923_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='link_twitter',
        ),
    ]
