# Generated by Django 2.0.8 on 2018-09-23 22:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_index_link_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='text_about',
            field=ckeditor.fields.RichTextField(verbose_name='Texto Sobre'),
        ),
    ]
