# Generated by Django 2.0.8 on 2018-09-27 02:15

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20180923_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '334x334', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Crop Imagem Sobre'),
        ),
    ]
