# Generated by Django 2.0.8 on 2018-09-29 22:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20180927_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='header_text',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Texto do Header'),
        ),
    ]
